spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=anshikasharma
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082
spring.security.enabled=false


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# If docker is not running, avoid app failing during startup
spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-manager.enabled=false

spring.jpa.hibernate.ddl-auto=update
