server.port=8083
spring.application.name=task-service
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=anshikasharma
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=deloitte-secret-key-2026-very-long-string-for-hmac-sha256
user.service.url=http://localhost:8081
