server.port=8082
spring.security.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable docker compose auto-lifecycle during local dev
spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-manager.enabled=false

